Repository rucio/rucio, pull requests merged in 2021-02, with the labels that each got.

#4290 Messaging: Don't encode subject for python3 Fix #4289
  lib/rucio/daemons/hermes/hermes.py
  lib/rucio/daemons/hermes/hermes2.py
Labels: Messaging

#4338 Core: Stop meta variable from being reused and re-encoded over and over Fix #4337
  lib/rucio/core/rule.py
Labels: Core & Internals

#4165 Testing:upload/download and xrd integration tests #2311
  .github/workflows/imagecache.yml
  .github/workflows/integration_tests.yml
  AUTHORS.rst
  etc/docker/test/matrix.yml
  etc/docker/test/matrix_integration_tests.yml
  lib/rucio/common/utils.py
  lib/rucio/rse/protocols/xrootd.py
  lib/rucio/tests/rsemgr_api_test.py
  lib/rucio/tests/test_rse_protocol_xrootd.py
  lib/rucio/tests/test_rucio_server.py
  tools/docker_activate_rses.sh
  tools/test/build_images.py
  tools/test/matrix_parser.py
  tools/test/run_tests.py
Labels: Testing
