Repository rucio/rucio, pull requests merged in 2022-02, with the labels that each got.

#5204 Transfers: delete fts-throttler. Closes #5203
  bin/rucio-conveyor-fts-throttler
  etc/rucio.cfg.template
  etc/rucio_multi_vo.cfg.template
  lib/rucio/daemons/conveyor/fts_throttler.py
  lib/rucio/tests/test_daemons.py
Labels: enhancement

#5244 Testing: disable test_conveyor #5243
  lib/rucio/tests/test_conveyor.py
Labels: Testing

#5276 Select containers based on release brach for Integration Tests (master)
  .github/workflows/integration_tests.yml
Labels: Testing

#5274 Select containers based on release brach for Integration Tests (1.26) Close #5256
  .github/workflows/integration_tests.yml
Labels: Testing

#5267 Traces: bulk updates for schemas #5265
  lib/rucio/common/schema/generic.py
  lib/rucio/core/trace.py
  lib/rucio/tests/test_trace.py
Labels: Traces
